[package]
name = "Video3dScanner"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
video-rs = { version = "0.1", features = ["ndarray"] }
ndarray = { version = "0.15" }
